apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqconnector.fullname" . }}
  labels: {{- include "mqconnector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
  selector: {{- include "mqconnector.selectorLabels" . | nindent 4 }}
